// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.11.4
// source: any.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AnyServiceClient is the client API for AnyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnyServiceClient interface {
	Call(ctx context.Context, in *AnyRequest, opts ...grpc.CallOption) (*AnyReply, error)
}

type anyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnyServiceClient(cc grpc.ClientConnInterface) AnyServiceClient {
	return &anyServiceClient{cc}
}

func (c *anyServiceClient) Call(ctx context.Context, in *AnyRequest, opts ...grpc.CallOption) (*AnyReply, error) {
	out := new(AnyReply)
	err := c.cc.Invoke(ctx, "/protos.AnyService/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnyServiceServer is the server API for AnyService service.
// All implementations must embed UnimplementedAnyServiceServer
// for forward compatibility
type AnyServiceServer interface {
	Call(context.Context, *AnyRequest) (*AnyReply, error)
	mustEmbedUnimplementedAnyServiceServer()
}

// UnimplementedAnyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAnyServiceServer struct {
}

func (UnimplementedAnyServiceServer) Call(context.Context, *AnyRequest) (*AnyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedAnyServiceServer) mustEmbedUnimplementedAnyServiceServer() {}

// UnsafeAnyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnyServiceServer will
// result in compilation errors.
type UnsafeAnyServiceServer interface {
	mustEmbedUnimplementedAnyServiceServer()
}

func RegisterAnyServiceServer(s grpc.ServiceRegistrar, srv AnyServiceServer) {
	s.RegisterService(&AnyService_ServiceDesc, srv)
}

func _AnyService_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnyServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AnyService/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnyServiceServer).Call(ctx, req.(*AnyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnyService_ServiceDesc is the grpc.ServiceDesc for AnyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.AnyService",
	HandlerType: (*AnyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _AnyService_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "any.proto",
}
